name: 'actions-s3-cache'
author: 'Bitnomial'
description: 'This action caches paths in S3.'
inputs:
  s3-bucket:
    description: 'An s3 bucket name to store cached data'
    required: true
  key:
    description: 'A key for storing and restoring the cache'
    required: true
  paths:
    description: 'A list of files, directories, and patterns to cache and restore'
    required: true
  compression:
    description: 'Specify the compression to use in tar'
    required: true
    default: 'bzip2'
runs:
  using: 'node12'
  main: 'dist/restore/index.js'
  post: 'dist/save/index.js'
  post-if: 'success()'
branding:
  icon: 'package'
  color: 'yellow'
